Upgrade SonarQube to 6.7.4 & PostgreSQL to 10.4
mwz/sonar-scala-docker pull request #5
Opened 2018-06-10 16:56 UTC by BalmungSan

Hope everything is ok.

2018-06-14 21:49 UTC, mwz requested changes

2018-06-14 21:49 UTC, mwz commented on README.md
> +Version | SonarQube | PostgreSQL | sonar-scala | sonar-scala-extra
The reason I didn't include the postgres column is that I haven't been versioning the docker-compose.yml file - just the docker images themselves, which don't have any dependency on postgres. Tbh, I don't think it's worth tracking the postgres version here.

2018-06-14 21:49 UTC, mwz commented on README.md
> +The project is licensed under the Apache License v2. See the [LICENSE file](LICENSE) for more details.|
Could you please remove the `|`?

2018-06-14 21:49 UTC, mwz commented on README_DOCKERHUB.md
> +- `2.6.0`, `latest` [Dockerfile](https://github.com/mwz/sonar-scala-docker/blob/master/2.6.0/Dockerfile), [(v2.6.0)](https://github.com/mwz/sonar-scala-docker/releases/tag/2.6.0)
Looks like you missed the `2.6.0-full` version here.

2018-06-14 21:49 UTC, mwz commented on README_DOCKERHUB.md
> +Version | SonarQube | PostgreSQL | sonar-scala | sonar-scala-extra
As mentioned previously, Postgres isn't included in the docker images and we should exclude the `PostgreSQL` column from this table.

2018-06-14 22:34 UTC, BalmungSan commented
Roger, I just pushed the changes 😄

2018-06-15 10:53 UTC, mwz approved these changes
Thanks! It looks good, I'll merge it and publish the images later today.

2018-06-15 22:39 UTC, merged